import AppKit

/// 轮询 NSPasteboard.changeCount，发现变化时把内容写入 HistoryStore。
@MainActor
final class ClipboardMonitor: NSObject {
    private let store: HistoryStore
    private let settings: AppSettings
    private var timer: Timer?
    private var lastChangeCount: Int = 0

    /// 暂停截止时间；nil 表示未暂停。到时间后自动恢复记录
    private(set) var pausedUntil: Date?

    var isPaused: Bool {
        guard let pausedUntil else { return false }
        return pausedUntil > Date()
    }

    func pause(for interval: TimeInterval) {
        pausedUntil = Date().addingTimeInterval(interval)
    }

    func resume() {
        pausedUntil = nil
    }

    /// 缓存当前前台应用 bundleID，比每次 tick 读取 frontmostApplication 更稳定
    private var frontmostBundleID: String?
    private var appBundleID: String?

    init(store: HistoryStore, settings: AppSettings) {
        self.store = store
        self.settings = settings
        self.appBundleID = Bundle.main.bundleIdentifier
        super.init()
        lastChangeCount = NSPasteboard.general.changeCount
        updateFrontmostApp()
        NotificationCenter.default.addObserver(
            self,
            selector: #selector(updateFrontmostApp),
            name: NSWorkspace.didActivateApplicationNotification,
            object: nil
        )
    }

    @objc private func updateFrontmostApp() {
        frontmostBundleID = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
    }

    func start() {
        timer = Timer.scheduledTimer(timeInterval: 0.5, target: self,
                                     selector: #selector(tick), userInfo: nil, repeats: true)
    }

    deinit {
        NotificationCenter.default.removeObserver(self, name: NSWorkspace.didActivateApplicationNotification, object: nil)
        timer?.invalidate()
    }

    /// 我们自己写剪贴板后调用，避免把回写的内容当成新条目再收一遍。
    func syncChangeCount() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    @objc private func tick() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastChangeCount else { return }
        lastChangeCount = pb.changeCount
        guard !isPaused else { return }

        let source = frontmostBundleID
        // 忽略应用列表（不区分大小写）
        if let source,
           settings.ignoredBundleIDs.contains(where: { $0.lowercased() == source.lowercased() }) {
            return
        }
        // 不记录本应用自己写入剪贴板的内容
        if let source, let appBundleID,
           source.lowercased() == appBundleID.lowercased() {
            return
        }
        // 机密内容（ConcealedType，密码管理器等标记）
        if settings.ignoreConfidential, hasType(in: pb, matching: "org.nspasteboard.ConcealedType") { return }
        // 瞬时内容（TransientType / AutoGeneratedType，其他应用生成的临时数据）
        if settings.ignoreTransient,
           hasType(in: pb, matching: "org.nspasteboard.TransientType")
            || hasType(in: pb, matching: "org.nspasteboard.AutoGeneratedType") { return }

        if let string = pb.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            store.addText(string, sourceBundleID: source)
        } else if let png = imageData(from: pb) {
            store.addImage(png, sourceBundleID: source)
        }
    }

    private func hasType(in pb: NSPasteboard, matching fragment: String) -> Bool {
        pb.types?.contains { $0.rawValue.contains(fragment) } ?? false
    }

    private func imageData(from pb: NSPasteboard) -> Data? {
        if let png = pb.data(forType: .png) { return png }
        if let tiff = pb.data(forType: .tiff),
           let rep = NSBitmapImageRep(data: tiff) {
            return rep.representation(using: .png, properties: [:])
        }
        return nil
    }
}
